package com.chowdhury.pocket;
import android.app.*;import android.os.*;import android.webkit.*;import android.content.*;import android.content.res.*;import android.appwidget.*;import java.util.*;
public class MainActivity extends Activity {
 WebView web; final java.util.ArrayList<WebView> printViews=new java.util.ArrayList<>();String exportData,exportMime;android.webkit.ValueCallback<android.net.Uri[]> fileCallback;
 public void onCreate(Bundle b){super.onCreate(b);if(b!=null){exportData=b.getString("exportData");exportMime=b.getString("exportMime");}web=new WebView(this);setContentView(web);web.setBackgroundColor(0xffF7F6F0);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(true);
 web.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(in.getSystemWindowInsetLeft(),in.getSystemWindowInsetTop(),in.getSystemWindowInsetRight(),in.getSystemWindowInsetBottom());return in;});
 web.setWebChromeClient(new WebChromeClient(){public boolean onShowFileChooser(WebView w,android.webkit.ValueCallback<android.net.Uri[]> cb,FileChooserParams params){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;try{startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE),2);}catch(Exception e){fileCallback.onReceiveValue(null);fileCallback=null;}return true;}});
 web.addJavascriptInterface(new Bridge(),"PocketNative");web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return true;}public void onPageFinished(WebView v,String u){bridgeLaunchIntent();}});web.loadUrl("file:///android_asset/index.html");}
 protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("exportData",exportData);b.putString("exportMime",exportMime);}
 protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);bridgeLaunchIntent();}
 /* A widget tap must reach the WebView on every resume, not only on the first page load. */
 private void bridgeLaunchIntent(){try{web.evaluateJavascript("applyLaunchIntent()",null);}catch(Exception e){}}
 /* UTF-8 so English, Bangla and currency symbols survive the JavaScript bridge. */
 static String decode(String payload){if(payload==null)return "";if(!payload.startsWith("base64:"))return payload;try{return new String(android.util.Base64.decode(payload.substring(7),android.util.Base64.DEFAULT),java.nio.charset.StandardCharsets.UTF_8);}catch(Exception e){return "";}}
 private void writeEncoded(java.io.OutputStream stream)throws java.io.IOException{stream.write(decode(exportData).getBytes(java.nio.charset.StandardCharsets.UTF_8));}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==1){if(result==RESULT_OK&&data!=null&&exportData!=null){try(java.io.OutputStream stream=getContentResolver().openOutputStream(data.getData())){if(stream==null)throw new java.io.IOException();writeEncoded(stream);stream.flush();android.widget.Toast.makeText(this,"File saved",0).show();if("application/json".equals(exportMime)){org.json.JSONObject current=new org.json.JSONObject(getSharedPreferences("pocket",0).getString("data","{}"));current.put("lastBackup",System.currentTimeMillis());current.put("backupRevision",Math.min(current.optLong("revision"),new org.json.JSONObject(decode(exportData)).optLong("revision")));if(getSharedPreferences("pocket",0).edit().putString("data",current.toString()).commit()){ExpenseWidget.refresh(this);web.evaluateJavascript("state=Pocket.migrate(JSON.parse(PocketNative.read()));render()",null);}}}catch(Exception e){android.widget.Toast.makeText(this,"File could not be saved",1).show();}}exportData=null;exportMime=null;}if(request==2&&fileCallback!=null){fileCallback.onReceiveValue(result==RESULT_OK&&data!=null?new android.net.Uri[]{data.getData()}:null);fileCallback=null;}}
 public class Bridge {
 @JavascriptInterface public void printReport(String html,String name){runOnUiThread(()->{WebView view=new WebView(MainActivity.this);printViews.add(view);view.getSettings().setJavaScriptEnabled(false);view.getSettings().setAllowFileAccess(false);view.getSettings().setAllowContentAccess(false);view.setWebViewClient(new WebViewClient(){boolean started=false;@Override public void onPageFinished(WebView v,String url){if(started)return;started=true;try{android.print.PrintManager manager=(android.print.PrintManager)getSystemService(Context.PRINT_SERVICE);if(manager==null)throw new IllegalStateException();android.print.PrintDocumentAdapter delegate=v.createPrintDocumentAdapter(name);android.print.PrintDocumentAdapter adapter=new android.print.PrintDocumentAdapter(){@Override public void onStart(){delegate.onStart();}@Override public void onLayout(android.print.PrintAttributes oldAttributes,android.print.PrintAttributes newAttributes,android.os.CancellationSignal signal,LayoutResultCallback callback,Bundle extras){delegate.onLayout(oldAttributes,newAttributes,signal,callback,extras);}@Override public void onWrite(android.print.PageRange[] pages,android.os.ParcelFileDescriptor destination,android.os.CancellationSignal signal,WriteResultCallback callback){delegate.onWrite(pages,destination,signal,callback);}@Override public void onFinish(){delegate.onFinish();v.destroy();printViews.remove(v);}};android.print.PrintAttributes.Builder attributes=new android.print.PrintAttributes.Builder().setMediaSize(android.print.PrintAttributes.MediaSize.ISO_A4);
 /* Unsupported attributes (unknown colour mode or a page size the printer rejects) must not break export. */
 /* ISO_A4 portrait at 300 dpi with 640 (1/1000 inch) margins, which matches the 13 mm @page margin in the report CSS. */
 android.print.PrintAttributes.Builder page=new android.print.PrintAttributes.Builder()
  .setMediaSize(android.print.PrintAttributes.MediaSize.ISO_A4)
  .setResolution(new android.print.PrintAttributes.Resolution("pocket-a4","300dpi",300,300))
  .setMinMargins(new android.print.PrintAttributes.Margins(640,640,640,640));
 try{manager.print(name,adapter,page.build());}catch(Exception preset){manager.print(name,adapter,new android.print.PrintAttributes.Builder().setMediaSize(android.print.PrintAttributes.MediaSize.ISO_A4).setMinMargins(new android.print.PrintAttributes.Margins(640,640,640,640)).build());}}catch(Exception e){v.destroy();printViews.remove(v);android.widget.Toast.makeText(MainActivity.this,"Printing unavailable on this device",1).show();}}});view.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);});}

 @JavascriptInterface public void exportFile(String text,String name,String mime){runOnUiThread(()->{exportData=text;exportMime=mime;try{startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType(mime).addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,name),1);}catch(Exception e){exportData=null;exportMime=null;android.widget.Toast.makeText(MainActivity.this,"No file picker available",1).show();}});}
 @JavascriptInterface public String read(){return getSharedPreferences("pocket",0).getString("data","{\"budget\":0,\"entries\":[]}");}
 @JavascriptInterface public boolean save(String json){try{org.json.JSONObject parsed=new org.json.JSONObject(json);boolean ok=getSharedPreferences("pocket",0).edit().putString("data",json).commit();if(ok){applyLocale(parsed.optString("language","en"));runOnUiThread(()->ExpenseWidget.refresh(MainActivity.this));}return ok;}catch(Exception e){return false;}}
 @JavascriptInterface public void syncWidgets(){runOnUiThread(()->ExpenseWidget.refresh(MainActivity.this));}
 /* Widget shortcuts: 0 = detailed, 1 = compact, 2..4 = Food, Transport, Groceries. */
 @JavascriptInterface public String launchIntent(){Intent i=getIntent();if(i==null||!i.getBooleanExtra("add",false))return "";org.json.JSONObject o=new org.json.JSONObject();try{o.put("add",true);String category=i.getStringExtra("category");if(category!=null)o.put("category",category);}catch(Exception e){}return o.toString();}
 @JavascriptInterface public void pin(boolean compact){runOnUiThread(()->{AppWidgetManager m=getSystemService(AppWidgetManager.class);if(m.isRequestPinAppWidgetSupported())m.requestPinAppWidget(new ComponentName(MainActivity.this,compact?CompactWidget.class:ExpenseWidget.class),null,null);else new AlertDialog.Builder(MainActivity.this).setMessage("Long-press your home screen, choose Widgets, then Pocket Expense.").setPositiveButton("OK",null).show();});}
 /* App language for the number/date formatting inside the exported report. */
 private void applyLocale(String language){if(language==null||language.isEmpty())return;try{Configuration config=new Configuration(getResources().getConfiguration());config.setLocale("bn".equals(language)?new Locale("bn","BD"):Locale.US);getResources().updateConfiguration(config,getResources().getDisplayMetrics());}catch(Exception e){}}}
}

